name: Run Python Script with latest version

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyPDF2
      - name: Run script
        run: |
          hanzi=$(cat input_test.txt)
          python main.py "$hanzi"
